// Applies the SQL migrations in packages/db/migrations (generated by drizzle-kit from src/schema.ts).
// Its own entry (@sotto/db/migrate): the web app never imports it, because bundlers resolve the
// `new URL("../migrations", import.meta.url)` below as an asset.
import { fileURLToPath } from "node:url";
import { migrate } from "drizzle-orm/postgres-js/migrator";
import { createDb } from "./client.ts";

export const MIGRATIONS_FOLDER = fileURLToPath(new URL("../migrations", import.meta.url));

export async function migrateDatabase(url: string): Promise<void> {
  const { db, close } = createDb(url, { max: 1 });
  try {
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await close();
  }
}
