// The logo components from the approved brand kit (step 4.2.1; design/brand-kit/BRAND-GUIDELINES.md):
// reads the outlined SVG files in design/brand-kit/logos/svg and writes
// packages/ui/src/brand/logos.tsx, React components with the files' own paths and colors, so the
// logo inherits no font and is never retyped. Run after the kit changes:
//   node scripts/generate-brand.ts           writes the file
//   node scripts/generate-brand.ts --check   exits 1 if the file is not what the kit gives
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const SOURCE = "design/brand-kit/logos/svg";
const TARGET = "packages/ui/src/brand/logos.tsx";
const FILES: { component: string; file: string; use: string }[] = [
  {
    component: "SottoLockupInk",
    file: "sotto-lockup-ink.svg",
    use: "The horizontal lockup on light grounds (the default).",
  },
  {
    component: "SottoLockupWhite",
    file: "sotto-lockup-white.svg",
    use: "The horizontal lockup on dark grounds (night, the sky).",
  },
  {
    component: "SottoMarkInk",
    file: "sotto-mark-ink.svg",
    use: "The mark alone, ink, for small spaces (the app header on a narrow screen), never under 24 pixels.",
  },
  {
    component: "SottoWordmarkWhite",
    file: "sotto-wordmark-white.svg",
    use: "The wordmark alone, white: the landing footer's large wordmark.",
  },
];
const ATTRIBUTES: Record<string, string> = {
  d: "d",
  fill: "fill",
  stroke: "stroke",
  "stroke-width": "strokeWidth",
  x: "x",
  y: "y",
  width: "width",
  height: "height",
};

function component({ component, file, use }: (typeof FILES)[number]): string {
  const svg = readFileSync(`${ROOT}${SOURCE}/${file}`, "utf8");
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1];
  if (!viewBox) throw new Error(`${file}: no viewBox`);
  const [, , w, h] = viewBox.split(/\s+/).map(Number);
  if (!w || !h) throw new Error(`${file}: bad viewBox`);
  if (/<text\b/.test(svg)) throw new Error(`${file}: holds text; the kit's logos are outlined`);
  const shapes = [...svg.matchAll(/<(path|rect)\b([^>]*?)\/>/g)].map(([, tag, attrs]) => {
    const props = [...(attrs ?? "").matchAll(/([a-z-]+)="([^"]*)"/g)].map(([, name, value]) => {
      const jsx = ATTRIBUTES[name ?? ""];
      if (!jsx) throw new Error(`${file}: unexpected attribute ${name}`);
      return `${jsx}="${value}"`;
    });
    return `      <${tag} ${props.join(" ")} />`;
  });
  if (shapes.length === 0) throw new Error(`${file}: no shapes`);
  return `/** ${use} From ${file}. */
export function ${component}({ height, decorative = false, ...rest }: LogoProps) {
  return (
    <svg
      viewBox="${viewBox}"
      height={height}
      width={(height * ${w}) / ${h}}
      {...(decorative ? { "aria-hidden": true } : { role: "img", "aria-label": "Sotto" })}
      focusable="false"
      {...rest}
    >
${shapes.join("\n")}
    </svg>
  );
}
`;
}

export function render(): string {
  return `// Generated by scripts/generate-brand.ts from design/brand-kit/logos/svg, the approved brand kit
// (step 4.2.1). Do not edit: change the kit, then run \`node scripts/generate-brand.ts\`.
import type { SVGProps } from "react";

export type LogoProps = Omit<SVGProps<SVGSVGElement>, "viewBox" | "children" | "width" | "height"> & {
  /** Height in pixels; the width follows the file's proportions. */
  height: number;
  /** True inside a link or button that already names Sotto. */
  decorative?: boolean;
};

${FILES.map(component).join("\n")}`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = render();
  if (process.argv.includes("--check")) {
    const current = readFileSync(`${ROOT}${TARGET}`, "utf8");
    if (current !== out) {
      console.error(`${TARGET} is not what ${SOURCE} gives: run node scripts/generate-brand.ts`);
      process.exit(1);
    }
    console.log(`ok: ${TARGET} matches ${SOURCE}`);
  } else {
    writeFileSync(`${ROOT}${TARGET}`, out);
    console.log(`wrote ${TARGET}`);
  }
}
